
// =============================================================================================
// This file was automatically generated by the Dapper.FastCRUD T4 Template
// Do not make changes directly to this file - edit the template configuration instead
// 
// The following settings were used to generate this file:
// 
//     Provider:                                          System.Data.SqlClient
//     Views included:                                    True
//     Relationships included:                            True
//     Default database column value generation analysis: False
// =============================================================================================
namespace NotesAPI.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Collections.Generic;
    /// <summary>
    /// Represents the 'Notes' table.
    /// </summary>
    [Table("Notes")]
    public partial class NoteEntity
    {
        /// <summary>
        /// Represents the column 'Id'.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public virtual Guid Id { get; set; }

        /// <summary>
        /// Represents the column 'Title'.
        /// </summary>
        public virtual string Title { get; set; }

        /// <summary>
        /// Represents the column 'Content'.
        /// </summary>
        public virtual string? Content { get; set; }
    }

}


